// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ6nCxGG_shHbxUx7xt3O3JPpSzf2jb64',
    appId: '1:1071931166442:web:554fd5d7b68046fa061193',
    messagingSenderId: '1071931166442',
    projectId: 'major-project-3b714',
    authDomain: 'major-project-3b714.firebaseapp.com',
    storageBucket: 'major-project-3b714.appspot.com',
    measurementId: 'G-9K2B8PZ35H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5_qBrp6kqF3wEsNBXzGHe3JVBkh5_OP4',
    appId: '1:1071931166442:android:ec6174ea7c1e0864061193',
    messagingSenderId: '1071931166442',
    projectId: 'major-project-3b714',
    storageBucket: 'major-project-3b714.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjd6U_3jDLAXGeA7YpQhFUOELbjgl8RaU',
    appId: '1:1071931166442:ios:4894e16b24e470d8061193',
    messagingSenderId: '1071931166442',
    projectId: 'major-project-3b714',
    storageBucket: 'major-project-3b714.appspot.com',
    iosClientId: '1071931166442-22vmr67qmc0dvl51plqb1m3cpaitv9kv.apps.googleusercontent.com',
    iosBundleId: 'com.akash.r500076108.majorProject',
  );
}
